import { Injectable } from '@angular/core';

@Injectable()
export class DianService {


  constructor() { }

  public obtenerUnidadesDeMedida(): any[] {
    return datosUnidadesDeMedida;
  }

  public obtenerUnidadDeMedida(id: string): {} {
    return datosUnidadesDeMedida.find(item => item.id == id);
  }
}


const datosUnidadesDeMedida = [
  { "id": "TF", "valor": "diez metros cuadrados" },
  { "id": "96", "valor": "diez mil galones (US) de carros" },
  { "id": "UH", "valor": "diez mil yardas" },
  { "id": "TPR", "valor": "diez pares" },
  { "id": "TR", "valor": "diez pies cuadrados" },
  { "id": "YT", "valor": "diez yardas" },
  { "id": "DZN", "valor": "docena" },
  { "id": "RA", "valor": "estante" },
  { "id": "A76", "valor": "galón" },
  { "id": "GLL", "valor": "galón" },
  { "id": "GLI", "valor": "galón (Reino Unido)" },
  { "id": "GB", "valor": "galón (US) por día" },
  { "id": "5C", "valor": "galón (US) por mil" },
  { "id": "GN", "valor": "galón bruto" },
  { "id": "GRM", "valor": "gramo" },
  { "id": "25", "valor": "gramo por centímetro cuadrado" },
  { "id": "23", "valor": "gramo por centímetro cúbico" },
  { "id": "G", "valor": "K	 gramo por kilogramo" },
  { "id": "GL", "valor": "gramo por litro" },
  { "id": "GF", "valor": "gramo por metro (gramo por 100 centímetros)" },
  { "id": "GM", "valor": "gramo por metro cuadrado" },
  { "id": "A93", "valor": "gramo por metro cúbico" },
  { "id": "GJ", "valor": "gramo por mililitro" },
  { "id": "KGM", "valor": "kilogramo" },
  { "id": "E4", "valor": "kilogramo bruto" },
  { "id": "B37", "valor": "kilogramo de fuerza" },
  { "id": "B40", "valor": "kilogramo de fuerza por metro cuadrado" },
  { "id": "KPH", "valor": "kilogramo de hidróxido de potasio (potasa cáustica)" },
  { "id": "KSH", "valor": "kilogramo de hidróxido de sodio (soda cáustica)" },
  { "id": "KNI", "valor": "kilogramo de nitrógeno" },
  { "id": "KPO", "valor": "kilogramo de óxido de potasio" },
  { "id": "KPP", "valor": "kilogramo de pentóxido de fósforo (anhídrido fosfórico)" },
  { "id": "KSD", "valor": "kilogramo de sustancia 90% seca" },
  { "id": "KNS", "valor": "kilogramo de sustancia nombrada" },
  { "id": "KUR", "valor": "kilogramo de uranio" },
  { "id": "KD", "valor": "kilogramo decimal" },
  { "id": "B32", "valor": "kilogramo metro cuadrado" },
  { "id": "B33", "valor": "kilogramo metro cuadrado por segundo" },
  { "id": "B31", "valor": "kilogramo metro por segundo" },
  { "id": "58", "valor": "kilogramo neto" },
  { "id": "32", "valor": "kilogramo por aire seco tonelada métrica" },
  { "id": "D5", "valor": "kilogramo por centímetro cuadrado" },
  { "id": "B34", "valor": "kilogramo por decímetro cúbico" },
  { "id": "3H", "valor": "kilogramo por kilogramo de producto" },
  { "id": "B35", "valor": "kilogramo por litro" },
  { "id": "KL", "valor": "kilogramo por metro" },
  { "id": "28", "valor": "kilogramo por metro cuadrado" },
  { "id": "KMQ", "valor": "kilogramo por metro cúbico" },
  { "id": "KI", "valor": "Kilogramo por milímetro de ancho" },
  { "id": "D74", "valor": "kilogramo por mol" },
  { "id": "3I", "valor": "kilogramo por pieza de producto" },
  { "id": "KGS", "valor": "kilogramo por segundo" },
  { "id": "KW", "valor": "kilogramos por milímetro" },
  { "id": "53", "valor": "kilogramos teóricos" },
  { "id": "KHZ", "valor": "kilohercio" },
  { "id": "KJO", "valor": "kilojoule" },
  { "id": "B41", "valor": "kilojoule per kelvin" },
  { "id": "B42", "valor": "kilojoule por kilogramo" },
  { "id": "B43", "valor": "kilojoule por kilogramo kelvin" },
  { "id": "B44", "valor": "kilojoule por mol" },
  { "id": "K6", "valor": "kilolitro" },
  { "id": "4X", "valor": "kilolitro por hora" },
  { "id": "KTM", "valor": "kilómetro" },
  { "id": "KMK", "valor": "kilometro cuadrado" },
  { "id": "KMH", "valor": "kilómetro por hora" },
  { "id": "B45", "valor": "kilomol" },
  { "id": "B46", "valor": "kilomol por metro cúbico" },
  { "id": "B47", "valor": "Kilonewton" },
  { "id": "B49", "valor": "kiloohm" },
  { "id": "KF", "valor": "kilopacket" },
  { "id": "KPA", "valor": "kilopascal" },
  { "id": "33", "valor": "kilopascales metros cuadrados por gramo" },
  { "id": "34", "valor": "kilopascales por milímetro" },
  { "id": "B51", "valor": "kilopond" },
  { "id": "84", "valor": "kilopound por pulgada cuadrada" },
  { "id": "KR", "valor": "KilorÃ¶ntgen" },
  { "id": "KJ", "valor": "kilosegmento" },
  { "id": "B52", "valor": "kilosegundo" },
  { "id": "B53", "valor": "kilosiemens" },
  { "id": "B54", "valor": "kilosiemens por metro" },
  { "id": "KTN", "valor": "kilotonne" },
  { "id": "KVR", "valor": "kilovar" },
  { "id": "KWT", "valor": "kilovatio" },
  { "id": "KWH", "valor": "kilovatios hora" },
  { "id": "B56", "valor": "kiloveber por metro" },
  { "id": "KVT", "valor": "kilovoltio" },
  { "id": "KVA", "valor": "kilovoltio – ampere" },
  { "id": "K3", "valor": "kilovoltio amperio hora reactiva" },
  { "id": "K2", "valor": "kilovoltios amperios reactivos de demanda" },
  { "id": "B55", "valor": "kilovoltios por metro" },
  { "id": "DD", "valor": "la licenciatura" },
  { "id": "05", "valor": "levantar" },
  { "id": "LBR", "valor": "libra" },
  { "id": "D96", "valor": "libra bruta" },
  { "id": "B3", "valor": "libra de bateo" },
  { "id": "D98", "valor": "libra de masa" },
  { "id": "LP", "valor": "libra liquida" },
  { "id": "WB", "valor": "libra mojada" },
  { "id": "PN", "valor": "libra neta" },
  { "id": "NY", "valor": "libra por aire seco tonelada métrica" },
  { "id": "GE", "valor": "libra por galón (US)" },
  { "id": "4U", "valor": "libra por hora" },
  { "id": "3E", "valor": "libra por libra de producto" },
  { "id": "29", "valor": "libra por mil pies cuadrados" },
  { "id": "P2", "valor": "libra por pie" },
  { "id": "FP", "valor": "libra por pie cuadrado" },
  { "id": "87", "valor": "libra por pie cúbico" },
  { "id": "3G", "valor": "libra por pieza de producto" },
  { "id": "64", "valor": "libra por pulgada cuadrada, calibre" },
  { "id": "LA", "valor": "libra por pulgada cúbica" },
  { "id": "PW", "valor": "libra por pulgada de ancho" },
  { "id": "PO", "valor": "libra por pulgada de longitud" },
  { "id": "RP", "valor": "libra por resma" },
  { "id": "DB", "valor": "libra seca" },
  { "id": "SD", "valor": "libra solida" },
  { "id": "24", "valor": "libra teórica" },
  { "id": "LBT", "valor": "libra troy" },
  { "id": "5F", "valor": "libras por mil" },
  { "id": "80", "valor": "libras por pulgada cuadrada absoluta" },
  { "id": "D63", "valor": "libro" },
  { "id": "DY", "valor": "libro de directorio" },
  { "id": "Z8", "valor": "línea de noticias de ágata" },
  { "id": "UB", "valor": "Línea de telecomunicaciones en servicio promedio." },
  { "id": "T0", "valor": "Línea de telecomunicaciones en servicio." },
  { "id": "LE", "valor": "lite" },
  { "id": "B2", "valor": "litera" },
  { "id": "LTR", "valor": "litro" },
  { "id": "LPA", "valor": "litro de alcohol puro" },
  { "id": "NE", "valor": "litro neto" },
  { "id": "LD", "valor": "litro por día" },
  { "id": "L2", "valor": "litro por minuto" },
  { "id": "B58", "valor": "litro por mol" },
  { "id": "C0", "valor": "llamada" },
  { "id": "LN", "valor": "longitud" },
  { "id": "5B", "valor": "lote" },
  { "id": "MTQ", "valor": "Metro cúbico" },
  { "id": "D90", "valor": "metro cúbico (neto)" },
  { "id": "A38", "valor": "metro cúbico por coulomb" },
  { "id": "MQH", "valor": "metro cúbico por hora" },
  { "id": "A39", "valor": "metro cúbico por kilogramo" },
  { "id": "A40", "valor": "metro cúbico por mol" },
  { "id": "MQS", "valor": "metro cúbico por segundo" }];
